Repository FinishLine-CKU/FinishLine_BE, pull requests merged in 2025-04, with the labels that each got.

#29 과목 데이터 삭제 기능
  Django_ws/graduation/extract.py
  Django_ws/graduation/migrations/0024_mydonelecture_can_delete.py
  Django_ws/graduation/models.py
  Django_ws/graduation/serializers.py
  Django_ws/graduation/urls.py
  Django_ws/graduation/views.py
  Django_ws/user/migrations/0012_user_date_time_joined.py
  Django_ws/user/migrations/0013_alter_user_date_time_joined.py
  Django_ws/user/migrations/0014_user_last_login.py
  Django_ws/user/migrations/0015_alter_user_last_login.py
Labels: enhancement

#30 연계전공 로직 활성화 및 재학생 인증 로직 개선
  Django_ws/graduation/extract.py
  Django_ws/graduation/liberCheck.py
  Django_ws/graduation/major_calculate.py
  Django_ws/graduation/views.py
  Django_ws/user/migrations/0016_rename_done_rest_user_done_general_rest.py
  Django_ws/user/models.py
  Django_ws/user/scraping.py
  Django_ws/user/views.py
Labels: bug

#31 경찰행정학부 추가 및 user_id 오류 제거
  Django_ws/graduation/extract.py
  Django_ws/graduation/views.py
Labels: bug

#34 일선 교과목 검사 로직 추가
  Django_ws/graduation/major_calculate.py
  Django_ws/graduation/rest_calculate.py
  Django_ws/graduation/views.py
  Django_ws/user/migrations/0017_user_done_rest.py
  Django_ws/user/models.py
Labels: documentation

#38 코드 컨벤셔닝 + 리팩토링, 정리
  Django_ws/graduation/major_calculate.py
  Django_ws/graduation/micro_degree_calculate.py
  Django_ws/graduation/migrations/0025_rename_total_credit_standard_total_standard.py
  Django_ws/graduation/migrations/0026_rename_major_credit_standard_major_standard.py
  Django_ws/graduation/migrations/0027_rename_general_essential_credit_standard_essential_ge_standatd.py
  Django_ws/graduation/migrations/0028_rename_general_selection_credit_standard_choice_ge_standard.py
  Django_ws/graduation/migrations/0029_rename_rest_credit_standard_rest_standard.py
  Django_ws/graduation/migrations/0030_rename_sub_major_credit_standard_sub_major_standard.py
  Django_ws/graduation/models.py
  Django_ws/graduation/sub_major_calculate.py
  Django_ws/graduation/views.py
  Django_ws/user/migrations/0018_rename_need_major_user_lack_major.py
  Django_ws/user/migrations/0019_rename_need_sub_major_user_lack_sub_major.py
  Django_ws/user/migrations/0020_rename_done_micro_degree_user_done_md.py
  Django_ws/user/migrations/0021_user_done_sub_major_rest.py
  Django_ws/user/models.py
  Django_ws/user/views.py
Labels: enhancement

#39 소단위전공 로직 추가 및 컨벤셔닝
  Django_ws/graduation/major_calculate.py
  Django_ws/graduation/micro_degree_calculate.py
  Django_ws/graduation/migrations/0031_rename_micro_degree_credit_standard_md_standard.py
  Django_ws/graduation/migrations/0032_rename_essential_ge_standatd_standard_essential_ge_standard.py
  Django_ws/graduation/models.py
  Django_ws/graduation/rest_calculate.py
  Django_ws/graduation/sub_major_calculate.py
  Django_ws/graduation/views.py
  Django_ws/user/migrations/0022_rename_micro_degree_user_md_user_done_md_rest.py
  Django_ws/user/migrations/0023_user_lack_md.py
  Django_ws/user/models.py
  Django_ws/user/views.py
Labels: enhancement
